# Site settings
title: 
email: contact.nicodev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nicolas Devaux est développeur Web front-end. Création, optimisation, refonte de sites internet, responsive design, optimisation SEO
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nicodev3.github.io" # the base hostname & protocol for your site
twitter_username: nicodevaux
github_username:  nicodev3
author: Nicolas Devaux
lang: fr_FR
twitter:
  username: nicodevaux

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids:      false
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false

kramdown:
   input: GFM

permalink: /:year/:month/:day/:title/

comments: true
# redcarpet:
#   extensions:
#     - hard_wrap
#     - no_intra_emphasis
#     - autolink
#     - strikethrough
#     - fenced_code_blocks
# Exclude directories and/or files from the conversion.
exclude: [node_modules, gulpfile.js, package.json, Gemfile, Gemfile.lock]

plugins:
  - jekyll-seo-tag