# Site settings
title: "Nicolas Devaux - Développeur Web Front-end"
email: contact.nicodev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nicolas Devaux est développeur Web front-end. Création, optimisation, refonte de sites internet, responsive design, optimisation SEO
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nicodev3.github.io" # the base hostname & protocol for your site
twitter_username: nicodevaux
github_username:  nicodev3
author: Nicolas Devaux
lang: fr_FR
twitter:
  username: nicodevaux

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids:      false
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false
  input: GFM

permalink: /:year/:month/:day/:title/

comments: true

# Exclude directories and/or files from the conversion.
exclude: [node_modules, gulpfile.js, package.json, Gemfile, Gemfile.lock, netlify.toml]

# Plugins pour Jekyll 4.x
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-mentions
  - jekyll-gist
  - jekyll-github-metadata

# Configuration pour les métadonnées GitHub
repository: nicodev3/nicodev3.github.io

# Configuration pour le feed RSS
feed:
  path: feed.xml
  limit: 10

# Configuration pour le sitemap
sitemap:
  changefreq: weekly
  priority: 0.5